#!/usr/bin/env python3
"""
⚡ Flashable-Engine: Live On-Device Flashing Simulation ⚡
Simulates the exact user recovery experience when flashing a package generated by Mehraan's Flashable-Engine.
"""

import sys
import os
import time

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def ui_print(text=""):
    print(text)
    sys.stdout.flush()
    time.sleep(0.04)


def main():
    ui_print()
    ui_print("============================================")
    ui_print("         Flashing Script By Mehraan")
    ui_print("============================================")
    ui_print()
    ui_print("Device: Infinix GT 20 Pro")
    ui_print("Codename: X6871")
    ui_print("Version: 15.1.2.180SP05OP001PF001AZ")
    ui_print("Maintainer: Mehraan")
    ui_print("============================================")
    ui_print()
    ui_print("- Target Device    : Verified X6871")
    ui_print("- Active Boot Slot : Slot A")
    ui_print()
    ui_print("Patching firmware to both slots")
    ui_print("- Flashing partition lk to both slots")
    ui_print("- Flashing partition md1img to both slots")
    ui_print("- Flashing partition preloader_raw to both slots")
    ui_print("- Flashing partition scp to both slots")
    ui_print("- Flashing partition spmfw to both slots")
    ui_print("- Flashing partition sspm to both slots")
    ui_print("- Flashing partition tee to both slots")
    ui_print()
    ui_print("Patching system")
    ui_print("- Flashing partition boot to both slots")
    ui_print("- Flashing partition dtbo to both slots")
    ui_print("- Flashing partition init_boot to both slots")
    ui_print("- Flashing partition vendor_boot to both slots")
    ui_print("- Flashing partition vbmeta to both slots")
    ui_print()
    ui_print("- Configuring AVB 2.0 (Vbmeta)")
    ui_print("  - AVB Status : Enabled")
    ui_print()
    ui_print("Patching super partitions")
    ui_print("- Flashing partition system_a")
    ui_print("- Flashing partition vendor_a")
    ui_print("- Flashing partition product_a")
    ui_print("- Flashing partition system_ext_a")
    ui_print()
    ui_print("============================================")
    ui_print("           Flashed Successfully!")
    ui_print("============================================")
    ui_print()


if __name__ == "__main__":
    main()
