#!/usr/bin/env python3
"""
Flashable-Engine: Live On-Device Flashing Simulation (Rama Style)
Simulates the exact user recovery experience when flashing a package generated by Mehraan's Flashable-Engine.
"""

import sys
import os
import time

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

def ui_print(text=""):
    print(text)
    sys.stdout.flush()
    time.sleep(0.05)

def main():
    ui_print()
    ui_print("============================================")
    ui_print("Flashable ROM By Mehraan")
    ui_print("Device     : POCO F3")
    ui_print("Codename   : alioth")
    ui_print("Version    : v1.0.0-Stable")
    ui_print("Maintainer : Mehraan")
    ui_print("============================================")
    ui_print()

    ui_print("Checking boot slot... _a")
    ui_print()

    ui_print("Patching firmware to both slot...")
    ui_print("- Flashing partition modem to both slots")
    ui_print("- Flashing partition dsp to both slots")
    ui_print("- Flashing partition bluetooth to both slots")
    ui_print("- Flashing partition tz to both slots")
    ui_print("- Flashing partition xbl to both slots")
    ui_print()

    ui_print("Patching system...")
    ui_print("- Flashing partition boot to both slots")
    ui_print("- Flashing partition dtbo to both slots")
    ui_print("- Flashing partition vendor_boot to both slots")
    ui_print("- Flashing partition vbmeta to both slots")
    ui_print()

    ui_print("- Configuring AVB 2.0 (Vbmeta)...")
    ui_print("  • AVB Status : Disabled [dm-verity & verification OFF]")
    ui_print()

    ui_print("Patching super partitions...")
    ui_print("- Flashing partition system")
    ui_print("- Flashing partition vendor")
    ui_print("- Flashing partition product")
    ui_print()

    ui_print("============================================")
    ui_print("ROM Installed Successfully!")
    ui_print("Flashing Script By Mehraan")
    ui_print("============================================")
    ui_print()

if __name__ == "__main__":
    main()
